### ISSUE TITLE
Doesnt seem to work locally

### ISSUE THREAD

**Issue by GiCl90** [op12no2/lozza-ui#2]
When i download the code zip and open index.htm and press play. It doesnt show the board. I am opening in Chrome

It works at https://op12no2.github.io/lozza-ui in chrome though

**Comment by op12no2** [comment]
Lozza is not really designed to be used like that as browsers generally do
not allow local file access for security reasons.

However I do personally test it locally in chrome by adding the
--allow-file-access-from-files command line option

E.g.

"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
--allow-file-access-from-files

Cheers,
Colin

**Comment by GiCl90** [comment]
Thank you very much! you are right it works online!
